### ISSUE TITLE
D1 was not declared in this scope -> settings

### ISSUE THREAD

**Issue by Beppi4U** [squix78/esp8266-plane-spotter-color#11]
I am getting instant compiling error on the settings.h file

// Tft library connectors
#define TFT_DC D2
**#define TFT_CS D1**
#define TOUCH_CS D3
#define TOUCH_IRQ  D4
#define LED_PIN D8

.....any suggestions for help??

Thanks 
Andreas

**Comment by squix78** [comment]
The D1 pin aliases are only known to the compiler when you select the correct board. Did you make sure that you have selected the Wemos D1 Mini? If you're using a different board then replace the D* names with pin numbers

**Comment by Beppi4U** [comment]
Aaaaaargh! Yep that was the problem! Thanks for helping out that fast!
Have a nice weekend!
