### ISSUE TITLE
How edit / open the enclosure.scad file

### ISSUE THREAD

**Issue by anthonyjclarke** [squix78/esp8266-plane-spotter-color#2]
Hi,  what OSX app do you use?

Tried http://www.openscad.org/ but says file invalid?

Thanks

**Comment by squix78** [comment]
The App you download from openscad.org is the correct one. .scad files are
just text files, so open the enclosure.scad in a text editor and see if
everything looks fine. Then you could even copy the file into OpenScad's
text editor...

Once you have the file open in OpenScad you can render it and then export
to STL.

Let me know if that didn't work...

Cheers.

2017-01-06 6:06 GMT+01:00 Anthony Clarke <notifications@github.com>:
