### ISSUE TITLE
support for other maps [not a issue]

### ISSUE THREAD

**Issue by reaper7** [squix78/esp8266-plane-spotter-color#4]
gmaps is more readable in my region,
maybe option for select map source?

code for gmaps (smaller file, faster render):
```
downloadFile("http://maps.googleapis.com/maps/api/staticmap?center="+ String(mapCenter_.lat) + "," + String(mapCenter_.lon)+"&zoom="+ String(zoom_)+"&size="+ String(mapWidth_) + "x" + String(mapHeight_)+"&format=jpg-baseline&maptype=roadmap", getMapName(), progressCallback);
```

**Comment by squix78** [comment]
cool suggestion and it really looks nice. I'm surprised that it works without API key...

**Comment by reaper7** [comment]
me too :)
so, 192px height map looks ok and we have a 4 lines for text,
maybe Dst from third line move to first or second line
and a third line used exclusively for: From CITY and Country if exists
and the fourth line, similarly, To CITY and Country if exists

in old OLED version I had such a modification

**Comment by squix78** [comment]
I implemented the switch. The constructor of the GeoMaps class now has one more parameter to indicate the MapProvider. Do you agree we can close this issue?

**Comment by reaper7** [comment]
👍
