### ISSUE TITLE
Is it possible to dim the display?

### ISSUE THREAD

**Issue by osos** [squix78/esp8266-plane-spotter-color#6]
I notice in your setup you have connected the LED-pin from the display to the Wemos D1 mini.

Can it sustain the power?

Can it be used to turn the backlight on/off?

Can it be used to dim the backlight? e.g. PWM output?

I know the ili9341 is capable, but it somehow depends on the wiring of the chip.

**Comment by Bodmer** [comment]
Some ILI9341 based boards have an onboard transistor to switch the LED current, others have the LED exposed with either no series R or a very low value one.

If you have a display with a transistor, then the LED brightness can be PWM controlled.

**Comment by osos** [comment]
Thanks. But how do i recognize which kind. I am not a that much into electronics.

**Comment by Bodmer** [comment]
@osos   Have you bought a display yet? If so can you post a picture of the back on the board?

**Comment by osos** [comment]
It is identical with this one: http://www.ebay.com/itm/2-4-SPI-TFT-LCD-Touch-Panel-Serial-Port-Module-with-PBC-ILI9341-3-3V-240x320-/112014412654

**Comment by Bodmer** [comment]
OK, make a visual check and [compare with this picture](http://i.imgur.com/cevUCYf.png) from the ebay link you provided with your actual board.  I have drawn an arrow on the picture that points to the LED transistor Q1. Note that sometimes ebay pictures show images of one board and supply a lightly different one, hence the suggestion of a detailed look at the board you have.

The presence of that transistor means you can turn on off or PWM the backlight LED using a digital pin from your processor board.

**Comment by osos** [comment]
@Bodmer, thanks
